### ISSUE TITLE
GraphQL Storefront - product grid

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/design#10]
***Tasks***
- [x] competitive research on industry standards as well as innovative product grids  (including homepages). 
- [x] Spec out and design out the needed functionality for a reaction vanilla product grid
- [x] Trim it back to a vanilla MVP version. 

***Deliverables***

- [x] Wire
- [x] Visual design (can be highlevel and fairly generic)
- [x] HIgh-lefl list of product grid requirements
- [ ] URL handling 

***Questions to consider***

- Tags, how does someone navigate through the catalog with tags
- Is the homepage different? - Yes? Shows category 
- What types of product displays - Feature image(hero image), homepage image, category image, different sizes of product images, image grids, carousels?,  
- Product states and how are they displayed? (sold-out, on sale, x-left,)
- How are variants displayed on the product grid? 
- Autoscroll vs pagination? If it autoscrolls it should have a way of getting to the different sections 
- Search/filter/attribute navigation
- On a category page it could display tags for navigation down the side vs multifaceted search

**Comment by cassytaylor** [comment]
Here's an analysis on a selection of product listing grids and homepages - 
https://drive.google.com/open?id=1v8q7jKVEJWPReCGSKPiwcu9rhyJ7Fq-2uEVxUv1_F84

**Comment by cassytaylor** [comment]
Product grid requirements -
https://docs.google.com/spreadsheets/d/1_whIDhSjW8RZ0N5VqpKwTMMuuR-KaT_FUSN6yIx5zTY/edit#gid=658304823
