### ISSUE TITLE
GraphQL Storefront - Cart

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/design#12]
***Tasks***
- [x] competitive research on industry standards as well as innovative shopping carts
- [x] Spec out and design out the needed functionality for a reaction vanilla cart
- [x] Trim it back to a vanilla MVP version. 

***Deliverables***

- [x] Wire
- [x] Visual design (can be highlevel and fairly generic)
- [x] HIgh-level list of cart requirements
- [ ] URL handling 

***Requirements***
Requirements are available here: https://docs.google.com/document/d/1BxEc_Oyw-cqdfJytsmj6eyZ_UUHXwj02ckffEmHfBpY/edit?usp=sharing

**Comment by cassytaylor** [comment]
Invision prototype for Cart (mini-cart version and side cart versions): https://invis.io/8RJ8T69G45A

**Comment by cassytaylor** [comment]
Zeplin screens for Cart - https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/dashboard?seid=5afc85e02b49da4621509ab6
