### ISSUE TITLE
GraphQL Storefront - Checkout

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/design#13]
***Tasks***
- [x] competitive research on industry standards as well as innovative Checkouts
- [x] Spec out and design out the needed functionality for a reaction vanilla checkout
- [x] Trim it back to a vanilla MVP version. 

***Deliverables***

- [x] Wire: https://projects.invisionapp.com/freehand/document/9s6p4qWE6
- [x] Visual design (can be highlevel and fairly generic)
- [x] HIgh-level list of checkout requirements
- [ ] URL handling 

***Requirements***
Requirements are available here: https://docs.google.com/document/d/11ZrMvKyzbagC_LdWzzmIyMh4897VODdVYpoSJP3QkLs/edit#heading=h.eobs3rqvtd1x

**Comment by cassytaylor** [comment]
Invision prototypes for Checkout are available here -

Guest checkout - https://invis.io/TQJ4J4BGHF4
Mobile guest checkout - https://invis.io/QAJ4J2ASF2T
Signed-in checkout - https://invis.io/EXJ4J587CHW

**Comment by cassytaylor** [comment]
Screens on Zeplin are available here -

Guest checkout - https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/dashboard?seid=5b02f512c2fcab5116adbd56
Mobile guest checkout - https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/dashboard?seid=5b02f561b0d8c3aa48617e18
Signed in checkout - https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/dashboard?seid=5afc85f3ee152ad33d9b5e12
