### ISSUE TITLE
GraphQL Storefront - product detail page (PDP)

### ISSUE THREAD

**Issue by cassytaylor** [reactioncommerce/design#37]
***Tasks***
- [x] competitive research on industry standards as well as innovative PDPs
- [x] Spec out and design out the needed functionality for a reaction vanilla PDP
- [x] Trim it back to a vanilla MVP version. 

***Deliverables***

- [x] Wire
- [x] Visual design (can be highlevel and fairly generic)
- [x] HIgh-level list of product grid requirements
- [ ] URL handling 

***Requirements***
TBD
