### ISSUE TITLE
GraphQL Storefront - mobile PDP

### ISSUE THREAD

**Issue by cassytaylor** [reactioncommerce/design#38]
***Tasks***
- [x] competitive research on industry standards as well as innovative PDPs
- [x] Spec out and design out the needed functionality for a reaction vanilla PDP
- [x] Trim it back to a vanilla MVP version. 

***Deliverables***

- [x] Wire
- [x] Visual design (can be highlevel and fairly generic)
- [ ] HIgh-level list of product grid requirements
- [ ] URL handling 

***Requirements***
TBD

**Comment by cassytaylor** [comment]
Invision prototype available here - https://invis.io/NMGT5MY6ZDU#/290707139_Homepage_-_Mobile
(navigate to the first item on the homepage - Wavefarer shorts. available actions: scroll, select color variant thumbnail, select size and color variants, add to cart)

Zeplin screens - https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/dashboard?seid=5afc85d0a22c1b4f1d366c6a
