### ISSUE TITLE
Navigation builder UI

### ISSUE THREAD

**Issue by rymorgan** [reactioncommerce/design#72]
### UI elements

* Navigation hierarchy tree
* Display pages available to navigation 
* Display tags that are available to navigation

### Requirements

- [x] Ability to make nav items and organize them into a hierarchy that goes 3 deep
- [x] Ability to add nav items based on tags (essentially tagged products give the ability to create categories)
- [ ] Ability to create tags
- [x] Ability to rename nav items something other than the tag or page name
- [x] Ability to see pages  (from the CMS?) that can be added to the nav items
- [x] Sorting for pages (alphabetical, newest)
- [x] Sorting for tags (alphabetical, newest)
- [x] Create multi column menus
- [ ] Ability to have nav items link to external pages
- [ ] Ability to search tags (likely from a search table element)
- [x] Ability to publish
- [ ] Ability to preview

### Outstanding questions

* How do we account for the shop all (shop all shirts? etc?”)

### Links
Dans' wire
[https://app.zenhub.com/files/125917656/d8c78d3d-42ee-48c8-8d07-8c400572f1b0/download](https://app.zenhub.com/files/125917656/d8c78d3d-42ee-48c8-8d07-8c400572f1b0/download)

Example tree functionality- 
https://angular-ui-tree.github.io/angular-ui-tree/#/basic-example

Competative research - 
https://www.youtube.com/watch?v=H0_Gn-luo58&feature=youtu.be

**Comment by rymorgan** [comment]
@cassytaylor Updated based on my notes from the meeting today.

**Comment by dancastellon** [comment]
@rymorgan & @cassytaylor - I have an updated requirement after reviewing the technical implementation with Eric. Operators should be able to publish both the navigation tree, and individual navigation item changes. For the tree, that means when an item is added or moved around. For an item, there should probably be "Save & Publish" and "Save" buttons in the edit form for an item on the left. There should also be a visual indicator when an item has unpublished changes, both on the left-hand list and when an item is in a tree.

Let me know if that makes sense. Thank you!

**Comment by cassytaylor** [comment]
That makes sense to me, @dancastellon ! Thanks for the heads up.

**Comment by dancastellon** [comment]
@cassytaylor & @rymorgan - One (hopefully) final minor change. Instead of a single button for publishing tree changes, can we have two buttons? Something like "Publish Tree Changes" and "Publish Tree & Item Changes"? Let me know if that makes sense. Thanks!

**Comment by rymorgan** [comment]
@dancastellon @cassytaylor  - I'd really love to avoid the multiple button solution. This sounds like a very confusing UI with too much specificity that a user won't understand. We may try some iterations that don't  involve multiple buttons.  I know publishing can get overly complicated quickly.  I think I'd prefer to have one publishing mechanism unless absolutely necessary. I think we can notify folks of what they are publishing and maybe that will achieve the same requirement.
